[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -P/dev/tty.usbserial-14110"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]
